### ISSUE TITLE
Add a way to write template code with a script tag inside the template itself.

### ISSUE THREAD

**Issue by akanix42** [meteor/blaze#94]
Pulled out of #75 for further discussion. I think this also ties into #15 (locally-scoped Blaze templates).

**Comment by nathantreid** [comment]
There's a number of ways we can handle this; I do think it's important to keep it as simple as possible.
Proposed syntax:

``` handlebars
<!-- bar.html -->
<template name="bar">
  bar!
</template>

<!-- foo.html -->
<template name="foo">
  {{> bar}}
  {{hello}}
</template>

<script>
  import bar from './bar.html'
  foo.helpers({
    bar,
    hello() {
      return "awesome";
    }
  })
</script>
```

**Comment by mitar** [comment]
Yes, I would make every `.html` file simply a module which exports all the templates defined there.

**Comment by mitar** [comment]
And I think this is independent from the script tag. But it could be done at the same time. Script tag would simply pass raw JavaScript in that place in the module.

**Comment by mitar** [comment]
@nathantreid: I see that you are working on this?

I would also suggest that we run post-processing and also allow other languages. So:

```
<script language="coffee">
  # CoffeeScript
</script>
```

`coffee` corresponds to the `coffee` file extension.

**Comment by nathantreid** [comment]
I think we're on the same page with the script tag - that's what the commit I just made to my `blaze-modules` package (referenced above) does - anything inside the script tags goes straight into the module output and is then run through Babel.

``` handlebars
<script>
// abc
</script>
<template name="test">
</template>
<script>
// xyz
</script>
```
becomes
``` js
// abc

Template.__checkName("test");
Template["test"] = new Template("Template.test", function () {
  var view = this;
  return "";
});

// xyz

**Comment by mitar** [comment]
Yes!

**Comment by nathantreid** [comment]
I agree on the post-processing (I want to also add a <style> tag that runs through CSS modules and also supports less, sass, etc) but I think that's potentially a much bigger issue due to the way Meteor's build system works. Given that we probably want to allow the user to pick their pre-/post-processors and install them separately, we'd need to create a pluggable post-processing setup.

**Comment by mitar** [comment]
`<style>` is also a great idea! But we should probably make it so that for now you just specify the language again. And for post- and pre-processing we leave it to Meteor toolchain to do it, if they will ever do it.

**Comment by nathantreid** [comment]
Specifying the language is the issue I'm referring to - unless we hardcode support for say, CoffeeScript, or create some sort of pluggable pre/post processing setup, the code will still be placed as is into the output js file, so if the code is CoffeeScript or anything else that isn't valid JS, Meteor will throw an error.

I think implementing the `<script>` tag for JavaScript is a good first step, and we can figure out the rest as a second step. So in the first implementation, you could just write `<script>` without specifying a language, and if we later on build support for other languages, we can add support for specifying them via an attribute like in your example, but the default (no attribute) would be JavaScript, just like it is in HTML.

**Comment by aadamsx** [comment]
We should absolutely allow for the ```<script>``` tag.  It would be nice sometimes to have everything in one file, specially when it's a smaller component -- It makes it easer to reason about in some circumstances.

**Comment by stubailo** [comment]
I would really prefer the following format:

```html
<template>
  <script>
    ...
  </script>
  <div>
    Stuff
  </div>
</template>
```

That would make each template a more self-contained block, and might let us remove some boilerplate, like, instead of:

```js
Template.templateName.onRendered(function () { ... });
```

Maybe you could just do:

```js
export function onRendered() {

}
```

And that module would be merged onto the template or something. That would also help with reducing the amount of global stuff.

**Comment by aadamsx** [comment]
> That would make each template a more self-contained block, and might let us remove some boilerplate

Yes, the ```<script>``` tag should be embedded within the ```<template>``` tag -- I agree.

I don't follow this line of code (probably because I'm not up to speed on modules/import and exports).
```
export function onRendered() {
 ...
}
```

Would this code be something like this? 

```handlebars
<template name="component">
  <script>
    export function onRendered() {
      // what would go here?
    }
  </script>
</template>
```

And if this was used in another template like so?

```handlebars
<template name="parent">
  <script>
    // import "component" template here?
    import '../imports/component/component.html';
  </script>

   <div>{{> component}}</div>
</template>
```

**Comment by nathantreid** [comment]
@aadamsx I think your last example would probably be more like this:
``` handlebars
<template name="parent">
  <script>
    // import "component" template here?
    import { component } from '../imports/component/component.html';
  </script>

   <div>{{> component}}</div>
</template>
```

**Comment by nathantreid** [comment]
And the contents of onRendered would generally be DOM manipulations: https://guide.meteor.com/blaze.html#onrendered-for-libs

**Comment by aadamsx** [comment]
@nathantreid thanks, I updated my code.

**Comment by aadamsx** [comment]
> And onRendered is fired

I understand, but is it needed to export the component template?

**Comment by aadamsx** [comment]
I use onRendered in my existing code, but is it needed to export?

Would this code be something like this? 

```handlebars
<!-- /imports/component/component.html -->
<template name="component">
  <script>
     // nothing needed here for whatever reason -- can even remove the <script> tag if we like
  </script>
</template>
```
Same code for parent:

```
<!-- /client/views/parent.html -->
<template name="parent">
  <script>
    // import "component" template here?
    import { component } from '../imports/component/component.html';
  </script>

   <div>{{> component}}</div>
</template>

**Comment by mitar** [comment]
> the code will still be placed as is into the output js file, so if the code is CoffeeScript or anything else that isn't valid JS, Meteor will throw an error.

No, but you can do this generally. CoffeeScript does it already in the opposite direction. If you have raw JavaScript inside CoffeeScript, it does this [call ecmascript](https://github.com/meteor/meteor/blob/devel/packages/coffeescript/plugin/compile-coffeescript.js#L89) on it.

So we should just take the argument and resolve to plugin and call its code. It seems you are more comfortable with this parsing code, so if you make framework around to get this argument in, I can look into how to pass it through build plugin before it is added to Blaze module.

> I think implementing the <script> tag for JavaScript is a good first step, and we can figure out the rest as a second step.

I would agree if I were not be personally motivated to have at least CoffeeScript. :-) So if you can prepare me structure, I can take time to make it work for at least CoffeeScript.

BTW, I can also give you permissions to work in a branch here in this repository. So that we can all work on the same branch.

**Comment by nathantreid** [comment]
The way I'm seeing it, if you exported a function named after a Blaze event (`onCreated`, `onRendered`, etc) it would be assigned to that event, and if you exported something else it would become a helper. 
As for browser events (click, submit, etc), I'm not sure how we'd keep support for legacy event maps.

So this code today:
``` handlebars
<template name="bar">
  bar!!
</template>
```
``` handlebars
<template name="foo">
  <div class="{{styles.container}}">
    <h1>Foo Header</h1>
    {{> bar}}
    {{sayHello}}
    {{someReactiveVariable}}
  </div>
</template>
```
``` js
import { Template } from 'meteor/templating'
import { ReactiveField } from 'meteor/peerlibrary:reactive-field'
import { styles } from './foo.scss'

const someReactiveVariable = new ReactiveField()

Template.foo.onCreated(function onCreated() {
  doSomething()
})

Template.foo.helpers({
  sayHello() {
    return "hello"
  },
  someReactiveVariable,
  styles
})

function doSomething() {
  // or not...
}
```

Would be rewritten like so:
``` handlebars
<template name="bar">
  bar!!
</template>
```
``` handlebars
<template name="foo">
  <script>
    import { ReactiveField } from 'meteor/peerlibrary:reactive-field'
    export { styles } from './foo.scss'
    export { bar } from './bar.html'

    export const someReactiveVariable = new ReactiveField()

    export function onCreated() {
      doSomething()
    }

    export function sayHello() {
      return "hello"
    }
    
    function doSomething() {
      // or not...
    }
  </script>
  <div class="{{styles.container}}">
    <h1>Foo Header</h1>
    {{> bar}}
    {{sayHello}}
    {{someReactiveVariable}}
  </div>
</template>
```

**Comment by mitar** [comment]
OK, I assumed that [this pull request](https://github.com/meteor/meteor/pull/5936) was merged in. I think we have a much better use case here now why accessing to other build plugins is useful. One can stack them together.

**Comment by stubailo** [comment]
> The way I'm seeing it, if you exported a function named after a Blaze event (onCreated, onRendered, etc) it would be assigned to that event, and if you exported something else it would become a helper. 

This sounds great. I just added `export` because then the stuff inside `script` could be thought of as a "module". Meaning the template just does `import * as template from 'the-script-tag'`, and then uses `template.onRendered`, `template.myHelper`, etc.

**Comment by aadamsx** [comment]
> I just added export because then the stuff inside script could be thought of as a "module".

I thought once you imported a template-component sub-template into a parent template, I considered the whole enchilada as a "module", and the Parent import-er would get everything -- included code/helpers/events -- contained within that sub-template.  

What's the significance of "hiding" some code and "showing" some code via an export?

**Comment by stubailo** [comment]
I'm saying you can have private functions inside the `script` tag that don't become helpers, and that could be shown via export or not.

**Comment by aadamsx** [comment]
> I'm saying you can have private functions inside the script tag that don't become helpers, and that could be shown via export or not.

I understand that, but why would you want to?

**Comment by nathantreid** [comment]
> What's the significance of "hiding" some code and "showing" some code via an export?

I write code with lots of little functions, and I don't want all of those passed to the Blaze template for 2 reasons off the top of my head:
1. Conflicts between helper names and data context names.
2. I'd like to visually declare what Blaze can access. I think that makes it much easier to reason about - these three functions are my Blaze helpers, the rest are internal to my code here. If Blaze had all of them available, I'd probably resort to naming the internal ones something `function _doSomething() {}`, and I'd really rather avoid that.

**Comment by aadamsx** [comment]
So this is a "show/hide" thing -- not there and not there.  component can see and has access to all helpers, events, etc declared within its ```<script>``` tag -- no matter the case.  Yet the parent of the component will not see this same code unless/until it's explicitly exported.

**Comment by stubailo** [comment]
> component can see and has access to all helpers, events, etc declared within its <script> tag -- no matter the case

I don't think that's what we are saying. This is more like it:

```js
function privateFunction() {
 ...
}

Template.x.helpers({
  actualHelper() {
   return privateFunction(....);
 }
});

Template.x.events({
  event() {
   return privateFunction(....);
 }
});
```

There should be a way to write a function that is _not_ a helper, or an event handler, or a callback, and is not accessible from anywhere outside of that script tag.

**Comment by aadamsx** [comment]
The component template can "see" and has access to all helpers, events, etc declared within its ```<script>``` tag -- no matter the case.  Yet the parent template of the component will not "see" this same code unless/until it's explicitly exported.

What if the parent template needs to pass context/data into the child -- do we expose a interface within the component template for such things via export?  Do we reverse the process and do an import of the parent within the child template to get the context/data of the parent?

**Comment by stubailo** [comment]
> The component template can "see" and has access to all helpers, events, etc declared within its script tag -- no matter the case.

I disagree. There should be a way to define random functions in there that nobody, including the template, can see, from outside this particular snippet of JS code.

**Comment by nathantreid** [comment]
@mitar That could work, if the other build plugin was set up specifically to allow such things (it would have to expose a method that could accept just the source we're handing it), but thanks to the [(sadly undocumented) `file.require` method](https://github.com/meteor/meteor/blob/05f65f9b2180efa6293289393e4fa0e3b1efa3a9/tools/isobuild/compiler-plugin.js#L355), we can probably make it work with npm packages. I still have to look into this more, it's been rattling around in my head since @benjamn mentioned it on a Meteor issue.

The next issue is how to do it with the simplest user experience. The user would have to have the option to configure the preprocessor for each language, ideally globally. To do this, we'd have to have some way of setting Blaze compiler options (like in package.json, perhaps). If not globally, the user would have to do it on every `<script>` tag:
`<script type="text/coffeescript" preprocessor="coffee-script"></script>` (the type attribute is there for syntax highlighting, and because that's the official coffescript script tag). The `preprocessor` attribute would specify the npm package to use.
If we used `package.json` - I'm not sure what MDG's official stance is on where to put package-specific options, but that's what [juliancwirko:postcss](https://github.com/juliancwirko/meteor-postcss) and my CSS modules package are using - then you could leave off the preprocessor attribute and have your `package.json` be something like:
``` js
{
  "name": "app",
  "scripts": {
    "start": "meteor run"
  },
  "blaze": {
    "preprocessors": {
      "text/coffeescript": "coffee-script",
      "stylesheet/scss": "my-custom-scss-transpiler"
    },
    "postprocessors": {
      "stylesheet/scss": "some-css-modules-transpiler"
    }
  }
}
```

**Comment by aadamsx** [comment]
> There should be a way to define random functions in there that nobody, including the 

Do you mean like this?

```handlebars
<!-- template.html -->
<template>
  <script>
    onCreated() {
      // template can 'see' me
      // ..
      doSomething() // external function
    }
  </script>
</template>
```

```javascript
// do-something.js
function doSomething() {
  // ...
}
```

**Comment by mitar** [comment]
I really disagree with having `<script>` tag inside a `<template>`. The whole beauty of Blaze is that it separates templates from code. If you do not like that, use React. :-) It also introduces all this issues with what is visible and not. I think `<script>` tag is just a shortcut so that you can have things inside the same file, but otherwise it should also work with two files, template and code.

I think this is simply much cleaner:

```handlebars
<script>
  import { styles } from './foo.scss'
  import { bar } from './bar.html'
</script>

<template name="foo">
  <div class="{{styles.container}}">
    <h1>Foo Header</h1>
    {{> bar}}
    {{sayHello}}
    {{someReactiveVariable}}
  </div>
</template>

<script>
  import { ReactiveField } from 'meteor/peerlibrary:reactive-field'

  foo.onCreated(() => {
    this.someReactiveVariable = new ReactiveField();
  
    doSomething()
  });

  foo.helpers({
    sayHello() {
      return "hello";
    }
  });

  function doSomething() {
    // or not...
  }
</script>
```

You could also use some wrappers around this to make it:

```handlebars
<template name="fooTemplate">
  <div class="{{(import './foo.scss').styles.container}}">
    <h1>Foo Header</h1>
    {{> (import './bar.html').bar}}
    {{sayHello}}
    {{someReactiveVariable}}
  </div>
</template>

<script>
  import { ReactiveField } from 'meteor/peerlibrary:reactive-field'

  export class foo extends fooTemplate {
    onCreated() {
      this.someReactiveVariable = new ReactiveField();
      
      doSomething();
    }

    sayHello() {
      return "hello";
    }
  }

  function doSomething() {
    // or not...
  }
</script>
```

**Comment by stubailo** [comment]
Don't worry, I'll start working on Blaze 3 with script tags this weekend :P

**Comment by mitar** [comment]
But I would be OK with support for both `script` outside and inside `template`. And for people who like inside, I think requiring `export` to be accessible from a template is a good thing. We should not pollute the namespace inside a template with everything inside `script`.

**Comment by mitar** [comment]
> Don't worry, I'll start working on Blaze 3 with script tags this weekend :P

Perfect, I will expect your pull request Sunday midnight. While you are it, please [merge this in as well](https://github.com/meteor/meteor/pull/5936) and add CoffeeScript support for code inside script tags.

**Comment by mitar** [comment]
> What if the parent template needs to pass context/data into the child -- do we expose a interface within the component template for such things via export? Do we reverse the process and do an import of the parent within the child template to get the context/data of the parent?

I think this should be explicit. So my proposal would be that `this` inside a template becomes current template (or we can also introduce `template` symbol to be backwards compatible). So then if child template has to access anything, parent first passes itself to it:

```handlebars
{{> child parent=template}}
```

And then child:

```handlebars
<template name="child">
  {{parent.bar}}
</template>
```

**Comment by stubailo** [comment]
haha, sorry I'm just trolling, I think you have good points.

**Comment by mitar** [comment]
You cannot take it back now anymore!

**Comment by mitar** [comment]
Somehow I would really like that templates would be classes. So that in the inside script example above by @nathantreid, that `sayHello` function would be a method on the `foo` class, so that I can extend the `foo` class, and override it with my own one, making a new template I can import somewhere else.

**Comment by nathantreid** [comment]
@mitar in your example, I'm currently not liking how the template magically gets access to the imports. There could very well be a number of imports that the template simply doesn't need access to, and you could run into conflicts between imports, helpers, and data context. Here's a modified real-world example with more imports:
``` handlebars
<template name="foo">
  <div class="{{styles.container}}">
    <h1>Foo Header</h1>
    {{sayHello}}
    {{someReactiveVariable}}
    {{#autoForm collection=fooCollection id="fooForm" type="insert" class=styles.form}}
      {{> afQuickField name="name"}}
      <button type="submit" class="btn btn-primary">Submit</button>
    {{/autoForm}}
  </div>
</template>
<script>
  import { Meteor } from 'meteor/meteor'
  import { FlowRouter } from 'meteor/kadira:flow-router'
  import { hookFormSuccess } from '/imports/client/ui/helpers/autoform'
  import { ReactiveField } from 'meteor/peerlibrary:reactive-field'
  import { styles } from './foo.scss'
  import { fooCollection } from '/imports/collections/fooCollection'

  const someReactiveVariable = new ReactiveField()

  foo.onCreated(function onCreated() {
    hookFormSuccess('fooForm', () => FlowRouter.go('over-the-rainbow'))
    doSomething()
  })

  foo.helpers({
    sayHello() {
      return "hello"
    },
    someReactiveVariable,
    styles
  })

  async function doSomething() {
    const data = await Meteor.callPromise('getData')
    someReactiveVariable(data)
  }
</script>
```
I'm also confused about 
> ``` js
> foo.onCreated(() => {
>    this.someReactiveVariable = new ReactiveField();
>
>    doSomething()
>  });
> ```

Since we now have a `this` context coming from the outer scope.

**Comment by mitar** [comment]
> The way I'm seeing it, if you exported a function named after a Blaze event (onCreated, onRendered, etc) it would be assigned to that event, and if you exported something else it would become a helper.

We can see this also as simply providing template class methods. Where `onCreated`, `onRendered` and so on are default class methods for the template. (Template class itself should also have static methods, for backwards compatibility, `onCreated` which registers a hook.)

> As for browser events (click, submit, etc), I'm not sure how we'd keep support for legacy event maps.

We should just introduce inline event handlers which hook to helpers.

**Comment by mitar** [comment]
> Since we now have a this context coming from the outer scope.

Ups, my mistake. This should not be `=>`, but a normal function. I will update it above.

**Comment by nathantreid** [comment]
I'm not a fan of the class structure, the idea seems nice but the reality seems annoying to me: 
``` html
<template name="fooTemplate">
```
```js 
export class foo extends fooTemplate {
```

Kinda silly, but I don't want to have 2 different names. :frowning:

**Comment by mitar** [comment]
> I'm currently not liking how the template magically gets access to the imports. 

Valid point.

> I'm not a fan of the class structure, the idea seems nice but the reality seems annoying to me: 

Valid point. Let me prepare another example.

BTW, should `<script>` be allowed only top-level inside `<template>`? Could we at least agree on that? And only one? Because otherwise it will be chaos.

**Comment by mitar** [comment]
My proposal:

```handlebars
<!-- Global script, content is not available inside template
     render function, but it is inside other script tags -->
<script>
  import { Meteor } from 'meteor/meteor'
  import { FlowRouter } from 'meteor/kadira:flow-router'
  import { hookFormSuccess } from '/imports/client/ui/helpers/autoform'
  import { ReactiveField } from 'meteor/peerlibrary:reactive-field'
  import { styles } from './foo.scss'
  import { fooCollection } from '/imports/collections/fooCollection'
  
  async function doSomething(template) {
    const data = await Meteor.callPromise('getData')
    template.someReactiveVariable(data)
  }
</script>

<template name="foo">
  <div class="{{styles.container}}">
    <h1>Foo Header</h1>
    {{sayHello}}
    {{someReactiveVariable}}
    {{#autoForm collection=fooCollection id="fooForm" type="insert" class=styles.form}}
      {{> afQuickField name="name"}}
      <button type="submit" class="btn btn-primary">Submit</button>
    {{/autoForm}}
  </div>
</template>

<!-- Or you can have it inside template if you prefer -->
<script for="foo">
  someReactiveVariable = new ReactiveField()

  onCreated() {
    hookFormSuccess('fooForm', () => FlowRouter.go('over-the-rainbow'))
    doSomething(this)
  }

  sayHello() {
    return "hello"
  }
    
  styles = styles
</script>
```

Which would be compiled into something like:

```javascript
import { Meteor } from 'meteor/meteor'
import { FlowRouter } from 'meteor/kadira:flow-router'
import { hookFormSuccess } from '/imports/client/ui/helpers/autoform'
import { ReactiveField } from 'meteor/peerlibrary:reactive-field'
import { styles } from './foo.scss'
import { fooCollection } from '/imports/collections/fooCollection'

async function doSomething(template) {
  const data = await Meteor.callPromise('getData')
  template.someReactiveVariable(data)
}

class foo extends Blaze.Template {
  renderFunction() {
    // Render the foo template.
  }

  someReactiveVariable = new ReactiveField()

  onCreated() {
    hookFormSuccess('fooForm', () => FlowRouter.go('over-the-rainbow'))
    doSomething(this)
  }

  sayHello() {
    return "hello"
  }
    
  styles = styles
}
```

Please observe that this is the easiest possible to implement. I literary just combine strings together into this template:

```
<code from any script tag before template>

class <templateName> extends Blaze.Template {
  renderFunction() {
    <code for rendering template>
  }

  <code inside script tag for template>
}
```

Personally, I think this also gives good balance between what you allow inside a template script tag (not complete JavaScript, but everything inside ES6 class body).

**Comment by mitar** [comment]
> it would have to expose a method that could accept just the source we're handing it

I think [we just need this merged in](https://github.com/meteor/meteor/pull/5936), and then we can pass `File` object with `data` as a string to `compileOneFile`. Something like:

```javascript
const plugin = Plugin._getCompilerByExtension('coffee').instantiatePlugin();
plugin.compileOneFile(new File({data: coffeeScript}))
```

(This code above is probably not completely correct.)

> The next issue is how to do it with the simplest user experience. The user would have to have the option to configure the preprocessor for each language, ideally globally. 

I think this is out of the scope of this. We are [discussing it a bit here](https://github.com/meteor/meteor/pull/7727#issuecomment-243607317), so it is something to think about, how to configure Meteor build plugins. (I think that `package.json` seems reasonable.) What I would do for now is the code above, which would for:

```
<script language="coffee">
</script>
```

call the code above. So I would use `language` (or `extension`) attribute, not "standard" `type` or something. So we do not have to map anything.

**Comment by mitar** [comment]
(But this support for other languages is probably not something which would work well with my proposal above which is pretty linked to ES6. So we might need some other way to make support for multiple languages.)

**Comment by mitar** [comment]
Alternatively, if you use `<script for>` then you get template as `Template` inside your script. So you can do things like:

```handlebars
<template name="Foo">
  <div class="{{styles.container}}">
    <h1>Foo Header</h1>
    {{sayHello}}
    {{someReactiveVariable}}
    {{#autoForm collection=fooCollection id="fooForm" type="insert" class=styles.form}}
      {{> afQuickField name="name"}}
      <button type="submit" class="btn btn-primary">Submit</button>
    {{/autoForm}}
  </div>
</template>

<!-- Or you can have it inside template if you prefer -->
<script for="Foo">
  class Foo extends Template {
    someReactiveVariable = new ReactiveField()

    onCreated() {
      hookFormSuccess('fooForm', () => FlowRouter.go('over-the-rainbow'))
      doSomething(this)
    }

    sayHello() {
      return "hello"
    }
    
    styles = styles

    fooCollection = fooCollection
  }
  
  return Foo
</script>
```

Which would be compiled into something like:

```javascript
class Foo extends Blaze.Template {
  renderFunction() {
    // Render the foo template.
  }
}

Foo = (function (Template) {
  class Foo extends Template {
    someReactiveVariable = new ReactiveField()

    onCreated() {
      hookFormSuccess('fooForm', () => FlowRouter.go('over-the-rainbow'))
      doSomething(this)
    }

    sayHello() {
      return "hello"
    }
    
    styles = styles

    fooCollection = fooCollection
  }
  
  return Foo;
})(Foo) || Foo;
```

Or, you could do instead:

```handlebars
<script for="Foo">
  Template.onCreated(function () {
    hookFormSuccess('fooForm', () => FlowRouter.go('over-the-rainbow'))
    doSomething(this)  
  });
  
  Template.helpers({  
    sayHello() {
      return "hello"
    },
    styles,
    fooCollection,
    someReactiveVariable
  });
</script>
```

And I could do:

```handlebars
<script for="Foo" language="coffee">
class Foo extends Template
  constructor: ->
    @someReactiveVariable = new ReactiveField()
    @styles = styles
    @fooCollection = fooCollection

  onCreated: ->
    hookFormSuccess 'fooForm', => FlowRouter.go('over-the-rainbow')
    doSomething @

  sayHello: ->
    "hello"
</script>
```

**Comment by aadamsx** [comment]
Would this PR be backwards compatible?  For example, say I'm on 1.4.1 and this PR is accepted and the Blaze version gets bumped up.  Could I somehow "Pin" the newly updated version of Blaze with this PR incorporated --- keep my older Blaze code -- yet write new Blaze code with the ```<script>``` tag embedded?

**Comment by mitar** [comment]
I think what I am proposing above should be backwards compatible.

**Comment by tcastelli** [comment]
I'm really up for this proposal, full template management with everything in one file would be a great step forward for making it super fast an easy to see where all comes from.

I've been looking to all of the proposals and in general all have very good points. I wouldn't like to user the "for=" on any script because I would place them where they are meant to be used, but that's my personal taste. I think I would go for something like this


````
<template name="component2">  
  <script lang="js">
   import { styles } from './foo.scss'
   import { whatever} from "whateverlib";
    rVar = new ReactiveVariable();
    name = this.name || "noname";
     styles = styles;
     function onRendered() {
           whatever();
     };
     function onCreated() {       
       console.log(this.name);
     } ;    
     export function fieldValue(attr) {
       return "the-value"+attr;
     };
     export function fireClick(e,t){
       rVar.set(e.currentValue);
       console.log(fieldValue())
     };        
  </script>
  <p class="event-fire" onClick={{fireClick}}>The Field Value: {{fieldValue}}</p>
</template>


<template name="parent">
  <script lang="js">
    import { component1 } from '../imports/component/component1.html';
    import { component2 } from '../imports/component/component2.html';
  </script>

   <div class="{{styles.container}}">{{> component1}}</div>
   <div>{{> component2 name="foobar"}}</div>
</template>
````
For event handling something like viewmodel would be great, but for now using helpers for click, change and so on would be enough i guess (Also this could be converted to "click .event-fire" by transpiler for custom events.

**Comment by aadamsx** [comment]
> I wouldn't like to user the "for=" on any script because I would place them where they are meant to be used, but that's my personal taste.

I agree with @tcastelli here.

**Comment by nathantreid** [comment]
@mitar I keep thinking about this as I work in Blaze, and I really like your `<script for>` version, without the `for` attribute. The more I think about it, the more I think I like the class structure as it gives a clear understanding of scope and will be increasingly familiar with JavaScript developers as time goes on.
So, I think I'm advocating going back to your `class foo extends fooTemplate` proposal.

I don't think the script tag should be embedded in the template tag, because that means you can't embed actual script tags in the template tag, for example Google Analytics:
``` html
<template>
  <script>
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-XXXXX-X']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</template>
```

**Comment by aadamsx** [comment]
> I don't think the script tag should be embedded in the template tag, because that means you can't embed actual script tags in the template tag, for example Google Analytics

> -- @nathantreid 

Does it matter if it's ```<script>```, can it be say ```<code>``` for example?  Just as long as its inside the ```<template>```.

**Comment by tcastelli** [comment]
That's a good point, we could make different tags like @aadamsx said, or use the famous lang attribute to indicate that script doesn't need to be processed but copied directly to onRendered.
I don't know, maybe saying lang="raw" or omitting it could mean a native script like the one @nathantreid has posted and lang="es2015" will mean an extension of the template class.

**Comment by nathantreid** [comment]
Using another tag is certainly a possibility - one of the things I'm keeping in mind is editor support, because I think that's very important to the developer experience.
I know for sure all my coworkers (and myself!) would switch to React rather than use something with no syntax highlighting, eslint support, code completion, etc.
Using the `<script>` tag in most editors gives you JavaScript syntax highlighting; use the `<code>` tag won't (at least not out of the box). Some editors (WebStorm, for instance) will allow you to specify the script type (CoffeeScript, etc) and provide syntax highlighting for that as well.

My goal is to make the Spacebars experience as simple and sweet as possible, and I think being able to use the `<script>` tag aligns with that. For JavaScript, there should be no attributes necessary, just drop in a `<script>` tag and away you go; for other languages, you will need to specify the language and preferably in a way that reduces the amount of typing you need to do. For example, before adding a `lang` attribute, we should see how many editors currently support `<script type="text/coffeescript">`. Given that that is the official syntax for including coffeescript in the browser, it seems far likelier that editors will provde syntax highlighting for it, and it would be redundant if you always had to type `<script type="text/coffeescript" lang="coffee">`.

**Comment by aadamsx** [comment]
Can't we have more than one ```<script>``` tag within our ```<template>``` tag?

**Comment by mitar** [comment]
I would definitely go for `<script>` because then we get IDE support for free.

I do not see why would you need something to go through transpiler and something not to? We are just supporting ES2016 and this is it? So if it is JavaScript, it always goes?

> because that means you can't embed actual script tags in the template tag, for example Google Analytics:

Why would you want to do that? Why not just use `<body>` for that?

But yes, in that case we could go for `<script language="bare">` (we use keyword `bare` in many other Meteor contexts, instead of `raw`).

**Comment by mitar** [comment]
After some thought I do not think we should go with `bare`. But instead using `for=""` inside the `<template>` if you want to make a top-level entry inside a `<template>`.

**Comment by mitar** [comment]
Also, you do not really want `<script>` inline code in output HTML. This is really so old school and could make you have issues with CSP, if you want that protection.

What I would propose is:

```html
<template>
  <script for="">
    Meteor.startup(function () {
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-XXXXX-X']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    });
  </script>
</template>
```

Or even without `Meteor.startup`. And this code would run when this module loads.

**Comment by mitar** [comment]
So my personal proposal for this (and some other things) is:
* change Blaze templates to be nicely extendable JavaScript classes
* move resolving of `this` and any symbols to methods of a class instead of a statically defined methods on `Template`
* add life-cycle and some other methods to this base Blaze class, a bit like Blaze Components

All this should be backwards compatible, but would allow:
* easy extending of the base template as mentioned above with `<script>`
* easy implementation of things like Blaze Components
* or anything even simpler, where you could for your template (or class of templates) change that `this` for example always points to the current template instance, and that any template helper is resolved only against the methods on the template instance; while keeping backwards compatibility

Then, I would have the following `<script>` features. Top-level:

````
<script lang="[coffee|coffeescript|js|javascript]" for="[name of the symbol in current scope]>
</script>

<template name="[name of the symbol in this scope]" class="[name of the base class]">
  <script lang="[coffee|coffeescript|js|javascript]" for="[empty string if top-level]">
  </script>
</template>
```

So you can have `<script>` tag or inside or outside (this is just syntax difference). Outside `for` defaults to empty string, inside `for` defaults to current template.

For supporting various languages, I am not sure we can use build plugins for them, but we can manually support few popular languages or make some changes to build plugins or provide our own extension point for languages. (I would allow both `js` and `javascript` to mean the same thing, and this would be also the default.)

Then, `class` tag would tell which basic class to use instead of the default `Blaze.Template`. So it just means that some sub-class of `Blaze.Template` would be used instead. So you will be able to do `<template class="BlazeComponent"></template>` and have that template instance be instance of this other JavaScript class.

`<script>` tags for a particular template would then get `Template` the current template class and you can do whatever you want there. If it returns a true value, then this is assigned to the template symbol outside.

**Comment by tcastelli** [comment]
In general this seems like a very broad and good approach to make everything easily extendable and easy to reason about. However i think when no "for=" (or if we keep the for="") is used, the script content should be moved to the template "class" onRendered. I'm still not sure of what will happen with nested scripts though...

And btw i think using class attribute for template is prone to errors, I would prefer something else like className in react.

**Comment by mitar** [comment]
> the script content should be moved to the template "class" onRendered

I think this is too specific. I do not see this as too much boilerplate if you want that code:

```html
<script>
  return class Foo extends Template {
    onRendered() {
      // you code here
    }
  }
</script>
```

And:

```html
<script>
  Template.onRendered(function () {
    // you code here
  });
</script>
```

(Both of those would be supported.)

> And btw i think using class attribute for template is prone to errors, I would prefer something else like className in react.

Too long. :-) We will have to write this a lot. :-)

One other crazy idea is that we could have custom elements inside Blaze. So you could do:

```
<Component name="Dialog">
</Component>
```

Which would be the same as:

```
<template name="Dialog" class="Component">
</template>
```

In this perspective, we should maybe respect web components standard and simply use `is`:

```
<template name="Dialog" is="Component">
</template>
```

**Comment by tcastelli** [comment]
> I think this is too specific. I do not see this as too much boilerplate if you want that code:

I don't think it's too specific, it is the standard way of using script codes like the one from @nathantreid, (either copy the script to onRendered if it depends on the DOM being attached, or on a place it on meteor startup if it's a general thing). For me it makes sense to allow this behaviour by default so people starting to learn Blaze can get it to work easily from their previous HTML.
And btw, what takes longer, to write className or to write all that boilerplate for a simple <script>? ;)

> In this perspective, we should maybe respect web components standard and simply use is:

Then we could go for` is=` directly, you know my thing about reusing for different meanings :)


About nested scripts, it seems like they are supported in HTML5 but I think from Blaze's perspective they don't make a lot of sense, especially since they will be used mostly with a template class as a context.

**Comment by mitar** [comment]
See https://www.npmjs.com/package/meteor-sfc which seems to implement this.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
